name: contacts_transfer
description: Aplicación para transferir contactos de una plataforma a otra
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  contacts_service: ^0.6.3
  permission_handler: ^10.2.0
  equatable: ^2.0.5
  cloud_firestore: ^4.5.0
  flutter_secure_storage: ^8.0.0
  uuid: ^3.0.7
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
